name: SAJulekalender
version: "1.0.0"
description: "SuperAwesoem Julekalender 2024"
main: hundeklemmen.superawesome.Julekalender
authors: [Hundeklemmen]
depend: [WorldEdit]
commands:
  julekalendersa:
    description: "Julekalender debug"
    usage: /julekalendersa